<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Jangalekat.Web</RootNamespace>
    <UserSecretsId>jangalekat-web-dev</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jangalekat.Application\Jangalekat.Application.csproj" />
    <ProjectReference Include="..\Jangalekat.Infrastructure\Jangalekat.Infrastructure.csproj" />
    <ProjectReference Include="..\Jangalekat.Persistence\Jangalekat.Persistence.csproj" />
  </ItemGroup>

</Project>
